import { createHash } from "node:crypto";
import { z } from "zod";
import { EntityProvenanceSchema } from "../../src/domain/entities";
import {
  StoryEntityKindSchema,
  StorySummarySchema,
  type StorySummary,
} from "./schema";

const AutoSummaryInputSchema = z.strictObject({
  logicalId: z.string().min(1),
  entityKind: StoryEntityKindSchema,
  summary: z.string().min(1),
  provenance: z.array(EntityProvenanceSchema).min(1),
});

const AutoPublishMetadataSchema = z.strictObject({
  releaseId: z.string().min(1),
  generatorName: z.string().min(1),
  generatedAt: z.iso.datetime(),
});

export type AutoSummaryInput = z.infer<typeof AutoSummaryInputSchema>;

export function createAutoGeneratedSummaries(
  input: AutoSummaryInput[],
  metadataInput: z.input<typeof AutoPublishMetadataSchema>,
): StorySummary[] {
  const metadata = AutoPublishMetadataSchema.parse(metadataInput);
  const parsed = input.map((item) => AutoSummaryInputSchema.parse(item));
  const seen = new Set<string>();

  for (const item of parsed) {
    if (seen.has(item.logicalId)) throw new Error(`duplicate summary logical ID: ${item.logicalId}`);
    seen.add(item.logicalId);
  }

  return parsed.map((item) => StorySummarySchema.parse({
    ...item,
    releaseId: metadata.releaseId,
    locale: "zh-CN",
    contentChecksum: `sha256:${createHash("sha256").update(item.summary, "utf8").digest("hex")}`,
    reviewStatus: "auto-generated",
    generator: {
      name: metadata.generatorName,
      generatedAt: metadata.generatedAt,
    },
  }));
}
