import { describe, expect, it } from "vitest";
import { createAutoGeneratedSummaries } from "./auto-publish";

describe("offline wiki automatic summary publishing", () => {
  it("creates checksummed records that remain explicitly unreviewed", () => {
    const records = createAutoGeneratedSummaries([{
      logicalId: "character:1",
      entityKind: "character",
      summary: "原创故事摘要。",
      provenance: [{
        sourceName: "HoYoverse Character",
        sourceUrl: "https://example.com/source",
        sourceRevision: "captured-2026-09-07",
        sourcePath: "data.list[0].sExt.story",
        sourceChecksum: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      }],
    }], {
      releaseId: "4.4-fixture",
      generatorName: "Codex",
      generatedAt: "2026-09-07T03:00:00.000Z",
    });

    expect(records).toEqual([{
      logicalId: "character:1",
      entityKind: "character",
      releaseId: "4.4-fixture",
      locale: "zh-CN",
      summary: "原创故事摘要。",
      contentChecksum: "sha256:ef3ad281972dbcdd4a2f01fd692a9eb7b606a65ed903772133d9dafa3e3c2bd9",
      reviewStatus: "auto-generated",
      generator: { name: "Codex", generatedAt: "2026-09-07T03:00:00.000Z" },
      provenance: [{
        sourceName: "HoYoverse Character",
        sourceUrl: "https://example.com/source",
        sourceRevision: "captured-2026-09-07",
        sourcePath: "data.list[0].sExt.story",
        sourceChecksum: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      }],
    }]);
  });

  it("rejects duplicate logical IDs before overwriting editorial data", () => {
    const input = {
      logicalId: "character:1",
      entityKind: "character" as const,
      summary: "原创故事摘要。",
      provenance: [{
        sourceName: "HoYoverse Character",
        sourceUrl: "https://example.com/source",
        sourceRevision: "captured-2026-09-07",
        sourcePath: "data.list[0].sExt.story",
        sourceChecksum: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      }],
    };

    expect(() => createAutoGeneratedSummaries([input, input], {
      releaseId: "4.4-fixture",
      generatorName: "Codex",
      generatedAt: "2026-09-07T03:00:00.000Z",
    })).toThrow(/duplicate.*character:1/i);
  });
});
