import type { LocalFullTextOverlayRecord } from "../lore/local-overlay";
import type { DocumentCatalog, LoreCoverageMetric, LoreFamily, LoreRecord, StorySummary } from "../schema";
import { anchorFor, escapeHtml, externalLink, htmlDocument, textToHtml } from "./html";
import type { RenderedVolume } from "./volumes";

const ENTRIES_PER_VOLUME = 200;

type FamilyDefinition = {
  family: LoreFamily;
  prefix: string;
  label: string;
  kinds: readonly { kind: string; label: string }[];
};

const FAMILY_DEFINITIONS: readonly FamilyDefinition[] = [
  {
    family: "divergent-universe", prefix: "04-差分宇宙", label: "差分宇宙",
    kinds: [
      { kind: "blessing", label: "祝福" },
      { kind: "equation", label: "方程" },
      { kind: "curio", label: "奇物" },
      { kind: "weighted-curio", label: "加权奇物" },
      { kind: "occurrence", label: "事件" },
      { kind: "tutorial", label: "教程" },
      { kind: "probability-museum", label: "概率博物馆" },
      { kind: "operational-record", label: "运作记录" },
    ],
  },
  {
    family: "worldview", prefix: "05-世界观", label: "世界观",
    kinds: [
      { kind: "aeon", label: "星神" },
      { kind: "path", label: "命途" },
      { kind: "faction", label: "派系" },
      { kind: "location", label: "地点" },
      { kind: "term", label: "词条" },
      { kind: "npc", label: "NPC" },
      { kind: "enemy", label: "敌人" },
    ],
  },
  {
    family: "mission", prefix: "06-剧情", label: "剧情",
    kinds: [
      { kind: "trailblaze", label: "开拓任务" },
      { kind: "companion", label: "同行任务" },
      { kind: "adventure", label: "冒险任务" },
      { kind: "permanent-event", label: "常驻活动剧情" },
      { kind: "limited-event", label: "限时活动剧情" },
    ],
  },
  {
    family: "collectible", prefix: "07-文本收藏", label: "文本收藏",
    kinds: [
      { kind: "readable", label: "书籍与读物" },
      { kind: "inventory-item", label: "物品背景" },
      { kind: "achievement", label: "成就" },
      { kind: "message", label: "短信与聊天" },
      { kind: "phonograph", label: "唱片" },
      { kind: "tutorial", label: "教程" },
      { kind: "other", label: "其他" },
    ],
  },
];

const RELATIONSHIP_LABELS: Record<LoreRecord["relationships"][number]["type"], string> = {
  "located-in": "位于",
  "member-of": "隶属于",
  follows: "后续",
  requires: "前置要求",
  features: "登场角色",
  mentions: "提及",
  "related-to": "相关",
};

type RecordLocation = { filename: string; name: string };

export type LoreVolumeRenderInput = {
  catalog: DocumentCatalog;
  summaries: StorySummary[];
  localOverlay: ReadonlyMap<string, LocalFullTextOverlayRecord>;
};

function compareLoreRecords(left: LoreRecord, right: LoreRecord): number {
  if (left.displayOrder !== null || right.displayOrder !== null) {
    if (left.displayOrder === null) return 1;
    if (right.displayOrder === null) return -1;
    if (left.displayOrder !== right.displayOrder) return left.displayOrder - right.displayOrder;
  }
  return left.name.localeCompare(right.name, "zh-CN") || left.logicalId.localeCompare(right.logicalId);
}

function partFilename(definition: FamilyDefinition, kindLabel: string, part: number): string {
  return `${definition.prefix}-${kindLabel}-${String(part).padStart(3, "0")}.html`;
}

function rejectionCount(metric: LoreCoverageMetric): number {
    + metric.rejectedLaterVersion
    + metric.rejectedAmbiguousVersion
    + metric.invalidRelationships
  return metric.missingSourceEvidence
    + Object.values(metric.importRejections).reduce((sum, count) => sum + count, 0);
}

function coverageLine(metric: LoreCoverageMetric): string {
  const baseline = metric.baselineStatus === "complete"
    ? `基准完整 · 预期：${metric.expected} · 覆盖率：${metric.percentage!.toFixed(1)}%`
    : "基准未建立 · 覆盖率不适用";
  const rejected = metric.importRejections;
  const details = `归属拒绝：未知类别 ${rejected.unknownKind} · 缺少文本 ${rejected.missingText} · 版本不明确 ${rejected.ambiguousRelease} · 来源格式错误 ${rejected.malformedSource}`;
  return `<p class="coverage"><strong>${baseline}</strong><br>结构化：${metric.structured} · 摘要：${metric.summaries}（审核 ${metric.reviewed}；自动生成 ${metric.autoGenerated}） · 本地全文：${metric.fullText} · 拒绝：${rejectionCount(metric)}<br>${details}</p>`;
}

function sources(record: LoreRecord): string {
  const unique = [...new Map(record.provenance.map((item) => [`${item.sourceUrl}|${item.sourceRevision}`, item])).values()];
  return `<div class="source"><strong>来源：</strong>${unique.map((item) => (
    `${externalLink(item.sourceUrl, item.sourceName)} · revision ${escapeHtml(item.sourceRevision)}`
  )).join("；")}</div>`;
}

function summarySection(record: LoreRecord, summaries: ReadonlyMap<string, StorySummary>): string {
  const summary = summaries.get(record.logicalId);
  if (!summary) return `<section><h3>故事摘要</h3><p class="missing">尚无原创故事摘要。</p></section>`;
  const attribution = summary.reviewStatus === "reviewed"
    ? `原创摘要 · ${escapeHtml(summary.reviewer.name)} 审核`
    : `原创摘要 · 自动生成 · 未经人工复核 · ${escapeHtml(summary.generator.name)}`;
  return `<section><h3>故事摘要</h3><p>${textToHtml(summary.summary)}</p><p class="meta">${attribution}</p></section>`;
}

function fullTextSection(overlay: LocalFullTextOverlayRecord | undefined): string {
  if (!overlay) return `<section><h3>全文</h3><p class="missing">本地全文未导入</p></section>`;
  const sections = [...overlay.sections].sort((left, right) => left.order - right.order);
  return `<section class="local-full-text"><h3>全文</h3><p class="local-notice">全文来自用户提供的本地资料；未上传 GitHub</p>${sections.map((section) => {
    const title = section.title === null ? "" : `<h4>${textToHtml(section.title)}</h4>`;
    const labels = [
      section.speaker === null ? null : `说话人：${escapeHtml(section.speaker)}`,
      section.branch === null ? null : `分支：${escapeHtml(section.branch)}`,
    ].filter((value): value is string => value !== null);
    return `<div class="lore-section">${title}${labels.length === 0 ? "" : `<p class="meta">${labels.join(" · ")}</p>`}<p>${textToHtml(section.body)}</p></div>`;
  }).join("")}</section>`;
}

function mechanicsSection(record: LoreRecord): string {
  if (record.family !== "divergent-universe" || !record.mechanics) return "";
  const mechanics = record.mechanics;
  const details = [
    mechanics.rarity === null ? null : `稀有度：${mechanics.rarity}`,
    mechanics.path === null ? null : `命途：${escapeHtml(mechanics.path)}`,
    mechanics.activationRequirement == null ? null : `激活条件：${escapeHtml(mechanics.activationRequirement)}`,
    mechanics.enhancementRequirement == null ? null : `强化条件：${escapeHtml(mechanics.enhancementRequirement)}`,
  ].filter((value): value is string => value !== null);
  return `<section><h3>能力效果</h3>${details.length === 0 ? "" : `<p class="meta">${details.join(" · ")}</p>`}<p>${textToHtml(mechanics.effect)}</p>${mechanics.enhancedEffect === null ? "" : `<h4>强化效果</h4><p>${textToHtml(mechanics.enhancedEffect)}</p>`}</section>`;
}

function relationshipSection(
  record: LoreRecord,
  locations: ReadonlyMap<string, RecordLocation>,
): string {
  const relationships = record.relationships.flatMap((relationship) => {
    const type = escapeHtml(RELATIONSHIP_LABELS[relationship.type]);
    if (relationship.external) {
      return [`<li><strong>${type}：</strong>${escapeHtml(relationship.targetLogicalId)} <span class="meta">（外部条目）</span></li>`];
    }
    const target = locations.get(relationship.targetLogicalId);
    if (!target) return [];
    return [`<li><strong>${type}：</strong><a href="${target.filename}#${anchorFor(relationship.targetLogicalId)}">${escapeHtml(target.name)}</a></li>`];
  });
  return relationships.length === 0 ? "" : `<section><h3>关系</h3><ul class="relationships">${relationships.join("")}</ul></section>`;
}

function recordLocationMap(catalog: DocumentCatalog): Map<string, RecordLocation> {
  const locations = new Map<string, RecordLocation>();
  for (const item of catalog.characters) locations.set(item.logicalId, { filename: "01-角色图鉴.html", name: item.name });
  for (const item of catalog.lightCones) locations.set(item.logicalId, { filename: "02-光锥图鉴.html", name: item.name });
  for (const item of catalog.relicSets) locations.set(item.logicalId, { filename: "03-遗器图鉴.html", name: item.name });
  for (const definition of FAMILY_DEFINITIONS) {
    for (const kind of definition.kinds) {
      const records = catalog.lore
        .filter((record) => record.family === definition.family && record.kind === kind.kind)
        .sort(compareLoreRecords);
      for (const [index, record] of records.entries()) {
        locations.set(record.logicalId, {
          filename: partFilename(definition, kind.label, Math.floor(index / ENTRIES_PER_VOLUME) + 1),
          name: record.name,
        });
      }
    }
  }
  return locations;
}

function renderFamilyIndex(
  input: LoreVolumeRenderInput,
  definition: FamilyDefinition,
  locations: ReadonlyMap<string, RecordLocation>,
): RenderedVolume {
  const familyCoverage = input.catalog.loreCoverage.families[definition.family];
  const groups = definition.kinds.map((kind) => {
    const records = input.catalog.lore
      .filter((record) => record.family === definition.family && record.kind === kind.kind)
      .sort(compareLoreRecords);
    return `<section><h2>${escapeHtml(kind.label)}</h2>${coverageLine(familyCoverage.kinds[kind.kind]!)}${records.length === 0
      ? `<p class="missing">当前版本无已收录条目。</p>`
      : `<ol class="toc">${records.map((record) => {
        const target = locations.get(record.logicalId)!;
        return `<li><a href="${target.filename}#${anchorFor(record.logicalId)}">${escapeHtml(record.name)}</a> <span class="meta">${escapeHtml(record.logicalId)}</span></li>`;
      }).join("")}</ol>`}</section>`;
  }).join("");
  const body = `<section><h2>覆盖状态</h2>${coverageLine(familyCoverage)}</section>${groups}`;
  return {
    filename: `${definition.prefix}-索引.html`,
    title: `${definition.label}索引`,
    html: htmlDocument(`${definition.label}索引`, `${input.catalog.release.gameVersion} · ${input.catalog.release.id}`, body),
    family: definition.family,
    group: "index",
  };
}

function renderRecord(
  record: LoreRecord,
  summaries: ReadonlyMap<string, StorySummary>,
  overlay: ReadonlyMap<string, LocalFullTextOverlayRecord>,
  locations: ReadonlyMap<string, RecordLocation>,
): string {
  return `<article class="entry" id="${anchorFor(record.logicalId)}">
    <h2>${escapeHtml(record.name)}</h2>
    <p class="meta">${escapeHtml(record.releaseId)} · ${escapeHtml(record.logicalId)}</p>
    <p>${textToHtml(record.description)}</p>
    ${mechanicsSection(record)}
    ${relationshipSection(record, locations)}
    ${summarySection(record, summaries)}
    ${fullTextSection(overlay.get(record.logicalId))}
    ${sources(record)}
    <p class="return"><a href="#top">返回目录</a></p>
  </article>`;
}

export function renderLoreVolumes(input: LoreVolumeRenderInput): RenderedVolume[] {
  const locations = recordLocationMap(input.catalog);
  const summaries = new Map(input.summaries
    .filter((summary) => summary.entityKind === "lore" && summary.releaseId === input.catalog.release.id)
    .map((summary) => [summary.logicalId, summary]));
  const volumes: RenderedVolume[] = [];
  for (const definition of FAMILY_DEFINITIONS) {
    volumes.push(renderFamilyIndex(input, definition, locations));
    for (const kind of definition.kinds) {
      const records = input.catalog.lore
        .filter((record) => record.family === definition.family && record.kind === kind.kind)
        .sort(compareLoreRecords);
      for (let offset = 0; offset < records.length; offset += ENTRIES_PER_VOLUME) {
        const part = Math.floor(offset / ENTRIES_PER_VOLUME) + 1;
        const partRecords = records.slice(offset, offset + ENTRIES_PER_VOLUME);
        const title = `${definition.label} · ${kind.label} · ${String(part).padStart(3, "0")}`;
        const toc = `<nav><h2>目录</h2><ol class="toc">${partRecords.map((record) => `<li><a href="#${anchorFor(record.logicalId)}">${escapeHtml(record.name)}</a></li>`).join("")}</ol></nav>`;
        const body = `${toc}${partRecords.map((record) => renderRecord(record, summaries, input.localOverlay, locations)).join("")}`;
        volumes.push({
          filename: partFilename(definition, kind.label, part),
          title,
          html: htmlDocument(title, `${input.catalog.release.gameVersion} · ${input.catalog.release.id}`, body),
          family: definition.family,
          group: kind.kind,
        });
      }
    }
  }
  return volumes;
}

export const LORE_FAMILY_INDEXES = FAMILY_DEFINITIONS.map((definition) => ({
  family: definition.family,
  label: definition.label,
  filename: `${definition.prefix}-索引.html`,
}));
