import { existsSync, readFileSync } from "node:fs";
import { z } from "zod";
import type { EditorialData } from "../editorial";
import type { LocalImportReport } from "./import/transaction";
import type { LoreCatalog } from "./catalog";
import type { LocalFullTextOverlayRecord } from "./local-overlay";
import type { LoreFamily, LoreRecord } from "./schema";

const KINDS: Record<LoreFamily, readonly string[]> = {
  "divergent-universe": ["blessing", "equation", "curio", "weighted-curio", "occurrence", "tutorial", "probability-museum", "operational-record"],
  worldview: ["aeon", "path", "faction", "location", "term", "npc", "enemy"],
  mission: ["trailblaze", "companion", "adventure", "permanent-event", "limited-event"],
  collectible: ["readable", "inventory-item", "achievement", "message", "phonograph", "tutorial", "other"],
};
const FAMILIES = Object.keys(KINDS) as LoreFamily[];

const IMPORT_REJECTION_FIELDS = {
  unknownKind: z.number().int().nonnegative(),
  missingText: z.number().int().nonnegative(),
  ambiguousRelease: z.number().int().nonnegative(),
  malformedSource: z.number().int().nonnegative(),
};
export const ImportRejectionCountsSchema = z.strictObject(IMPORT_REJECTION_FIELDS);
export type ImportRejectionCounts = z.infer<typeof ImportRejectionCountsSchema>;

const COVERAGE_FIELDS = {
  baselineStatus: z.enum(["complete", "missing"]),
  expected: z.number().int().nonnegative().nullable(),
  structured: z.number().int().nonnegative(),
  summaries: z.number().int().nonnegative(),
  reviewed: z.number().int().nonnegative(),
  autoGenerated: z.number().int().nonnegative(),
  fullText: z.number().int().nonnegative(),
  missingSourceEvidence: z.number().int().nonnegative(),
  rejectedLaterVersion: z.number().int().nonnegative(),
  rejectedAmbiguousVersion: z.number().int().nonnegative(),
  invalidRelationships: z.number().int().nonnegative(),
  importRejections: ImportRejectionCountsSchema,
  percentage: z.number().nonnegative().nullable(),
};

function validateBaselineMetric(metric: {
  baselineStatus: "complete" | "missing";
  expected: number | null;
  structured: number;
  summaries: number;
  reviewed: number;
  autoGenerated: number;
  fullText: number;
  percentage: number | null;
}, context: z.RefinementCtx): void {
  if (metric.baselineStatus === "missing" && (metric.expected !== null || metric.percentage !== null)) {
    context.addIssue({ code: "custom", message: "missing lore baselines cannot report expected counts or percentages" });
  }
  if (metric.baselineStatus === "complete" && (metric.expected === null || metric.percentage === null)) {
    context.addIssue({ code: "custom", message: "complete lore baselines require expected counts and percentages" });
  }
  if (metric.summaries > metric.structured || metric.fullText > metric.structured
      || metric.reviewed > metric.summaries || metric.autoGenerated > metric.summaries) {
    context.addIssue({ code: "custom", message: "lore coverage component counts exceed their admitted parent count" });
  }
  if (metric.reviewed + metric.autoGenerated !== metric.summaries) {
    context.addIssue({ code: "custom", message: "reviewed and auto-generated lore counts must exactly partition summaries" });
  }
  if (metric.baselineStatus === "complete" && metric.expected !== null && metric.percentage !== null) {
    if (metric.structured > metric.expected) {
      context.addIssue({ code: "custom", message: "structured lore exceeds its complete expected baseline" });
    }
    const expectedPercentage = metric.expected === 0 ? 100 : (metric.structured / metric.expected) * 100;
    if (metric.percentage !== expectedPercentage) {
      context.addIssue({ code: "custom", message: "lore coverage percentage does not match structured/expected" });
    }
  }
}

export const LoreCoverageMetricSchema = z.strictObject(COVERAGE_FIELDS).superRefine(validateBaselineMetric);
export const LoreFamilyCoverageSchema = z.strictObject({
  ...COVERAGE_FIELDS,
  kinds: z.record(z.string(), LoreCoverageMetricSchema),
}).superRefine((family, context) => {
  validateBaselineMetric(family, context);
  validateAggregate(family, Object.values(family.kinds), context, "kind");
});
export const LoreCoverageReportSchema = z.strictObject({
  families: z.strictObject({
    "divergent-universe": LoreFamilyCoverageSchema,
    worldview: LoreFamilyCoverageSchema,
    mission: LoreFamilyCoverageSchema,
    collectible: LoreFamilyCoverageSchema,
  }),
  totals: LoreCoverageMetricSchema,
  unattributedImportRejections: ImportRejectionCountsSchema,
}).superRefine(({ families }, context) => {
  for (const [family, report] of Object.entries(families)) {
    const actual = Object.keys(report.kinds).sort();
    const expected = [...KINDS[family as LoreFamily]].sort();
    if (JSON.stringify(actual) !== JSON.stringify(expected)) {
      context.addIssue({ code: "custom", path: ["families", family, "kinds"], message: "lore coverage kinds must exactly match the approved taxonomy" });
    }
  }
}).superRefine(({ families, totals }, context) => {
  validateAggregate(totals, Object.values(families), context, "family");
});

export type LoreCoverageMetric = z.infer<typeof LoreCoverageMetricSchema>;
export type LoreFamilyCoverage = z.infer<typeof LoreFamilyCoverageSchema>;
export type LoreCoverageReport = z.infer<typeof LoreCoverageReportSchema>;

type InvalidRelationshipCounts = Partial<Record<LoreFamily, Partial<Record<string, number>>>>;
type ImportRejectionsById = Map<string, ImportRejectionCounts>;

const AGGREGATE_FIELDS = [
  "structured", "summaries", "reviewed", "autoGenerated", "fullText", "missingSourceEvidence",
  "rejectedLaterVersion", "rejectedAmbiguousVersion", "invalidRelationships",
] as const;

function emptyImportRejections(): ImportRejectionCounts {
  return { unknownKind: 0, missingText: 0, ambiguousRelease: 0, malformedSource: 0 };
}

function sumImportRejections(values: readonly ImportRejectionCounts[]): ImportRejectionCounts {
  return values.reduce((sum, value) => ({
    unknownKind: sum.unknownKind + value.unknownKind,
    missingText: sum.missingText + value.missingText,
    ambiguousRelease: sum.ambiguousRelease + value.ambiguousRelease,
    malformedSource: sum.malformedSource + value.malformedSource,
  }), emptyImportRejections());
}

function validateAggregate(
  aggregate: LoreCoverageMetric,
  members: readonly LoreCoverageMetric[],
  context: z.RefinementCtx,
  memberName: "kind" | "family",
): void {
  for (const field of AGGREGATE_FIELDS) {
    if (aggregate[field] !== members.reduce((sum, member) => sum + member[field], 0)) {
      context.addIssue({ code: "custom", path: [field], message: `lore coverage total must equal its ${memberName} sum` });
    }
  }
  const expectedRejections = sumImportRejections(members.map((member) => member.importRejections));
  if (JSON.stringify(aggregate.importRejections) !== JSON.stringify(expectedRejections)) {
    context.addIssue({ code: "custom", path: ["importRejections"], message: `import rejection total must equal its ${memberName} sum` });
  }
}

const ImportRejectionSchema = z.strictObject({
  sourcePath: z.string(),
  logicalId: z.string().nullable(),
  reason: z.enum(["unknown-kind", "missing-text", "ambiguous-release", "malformed-source"]),
  detail: z.enum([
    "required-layout-missing", "invalid-directory-json", "release-evidence-mismatch", "entry-not-declared",
    "category-not-mapped", "entry-file-not-declared", "entry-read-failed", "no-allowlisted-text",
    "display-name-empty", "invalid-table-json", "row-kind-not-approved", "story-not-found",
    "referenced-text-missing", "duplicate-entry-id", "duplicate-excel-row-id", "duplicate-story-id",
  ]),
});
const ImportReportSchema = z.strictObject({
  status: z.enum(["accepted", "rejected"]),
  releaseId: z.string(),
  acceptedCount: z.number().int().nonnegative(),
  rejectedCount: z.number().int().nonnegative(),
  inputChecksums: z.array(z.string().regex(/^sha256:[a-f0-9]{64}$/)),
  outputChecksum: z.string().regex(/^sha256:[a-f0-9]{64}$/).nullable(),
  warnings: z.array(z.literal("backup-cleanup-pending")),
  rejection: z.strictObject({
    reason: z.enum(["manifest-validation-failed", "adapter-unsupported", "adapter-rejected", "source-validation-failed", "canonical-validation-failed", "staging-failed", "promotion-failed", "recovery-failed"]),
    sourcePaths: z.array(z.string()),
    recoveryNames: z.array(z.string()),
    items: z.array(ImportRejectionSchema),
  }).nullable(),
}).superRefine((report, context) => {
  const accepted = report.status === "accepted";
  if (accepted && (report.rejection !== null || report.outputChecksum === null || report.rejectedCount !== 0)) {
    context.addIssue({ code: "custom", message: "accepted import reports cannot contain rejection state" });
  }
  if (!accepted && (report.rejection === null || report.outputChecksum !== null || report.acceptedCount !== 0)) {
    context.addIssue({ code: "custom", message: "rejected import reports require rejection state" });
  }
});

export function loadLocalImportReport(path: string | undefined): LocalImportReport | undefined {
  if (path === undefined || !existsSync(path)) return undefined;
  return ImportReportSchema.parse(JSON.parse(readFileSync(path, "utf8"))) as LocalImportReport;
}

function emptyMetric(): LoreCoverageMetric {
  return {
    baselineStatus: "missing", expected: null, structured: 0, summaries: 0, reviewed: 0,
    autoGenerated: 0, fullText: 0, missingSourceEvidence: 0, rejectedLaterVersion: 0,
    rejectedAmbiguousVersion: 0, invalidRelationships: 0, importRejections: emptyImportRejections(), percentage: null,
  };
}

function percentage(expected: number, structured: number): number {
  if (expected === 0) {
    if (structured !== 0) throw new Error("a zero-entry complete baseline cannot contain structured lore records");
    return 100;
  }
  return (structured / expected) * 100;
}

function rejectionField(reason: "unknown-kind" | "missing-text" | "ambiguous-release" | "malformed-source"): keyof ImportRejectionCounts {
  return ({
    "unknown-kind": "unknownKind",
    "missing-text": "missingText",
    "ambiguous-release": "ambiguousRelease",
    "malformed-source": "malformedSource",
  } as const)[reason];
}

function classifyImportRejections(
  report: LocalImportReport | undefined,
  releaseId: string,
  committedIds: ReadonlySet<string>,
): { byId: ImportRejectionsById; unattributed: ImportRejectionCounts } {
  const result = { byId: new Map<string, ImportRejectionCounts>(), unattributed: emptyImportRejections() };
  if (!report || report.releaseId !== releaseId || report.status !== "rejected" || !report.rejection) return result;
  const parsed = ImportReportSchema.parse(report);
  for (const item of parsed.rejection?.items ?? []) {
    const field = rejectionField(item.reason);
    if (item.logicalId === null || !committedIds.has(item.logicalId)) {
      result.unattributed[field] += 1;
      continue;
    }
    const counts = result.byId.get(item.logicalId) ?? emptyImportRejections();
    counts[field] += 1;
    result.byId.set(item.logicalId, counts);
  }
  return result;
}

function metricForRecords(
  records: readonly LoreRecord[],
  summaries: EditorialData["summaries"],
  overlay: ReadonlyMap<string, LocalFullTextOverlayRecord>,
  invalidRelationships: number,
  importRejectionsById: ImportRejectionsById,
): LoreCoverageMetric {
  const ids = new Set(records.map((record) => record.logicalId));
  const matching = summaries.filter((summary) => (
    summary.entityKind === "lore" && ids.has(summary.logicalId) && summary.releaseId === records[0]?.releaseId
  ));
  const summaryIds = new Set(matching.map((summary) => summary.logicalId));
  const reviewed = new Set(matching.filter((summary) => summary.reviewStatus === "reviewed").map((summary) => summary.logicalId));
  const autoGenerated = new Set(matching.filter((summary) => summary.reviewStatus === "auto-generated").map((summary) => summary.logicalId));
  return {
    ...emptyMetric(),
    structured: ids.size,
    summaries: summaryIds.size,
    reviewed: reviewed.size,
    autoGenerated: autoGenerated.size,
    fullText: [...ids].filter((id) => overlay.has(id)).length,
    missingSourceEvidence: records.filter((record) => record.provenance.length === 0).length,
    invalidRelationships,
    importRejections: sumImportRejections([...ids].map((id) => importRejectionsById.get(id) ?? emptyImportRejections())),
  };
}

export function buildLoreCoverage(input: {
  catalog: LoreCatalog;
  summaries: EditorialData["summaries"];
  localOverlay: ReadonlyMap<string, LocalFullTextOverlayRecord>;
  importReport?: LocalImportReport;
  invalidRelationships?: InvalidRelationshipCounts;
}): LoreCoverageReport {
  const classifiedRejections = classifyImportRejections(
    input.importReport,
    input.catalog.releaseId,
    new Set(input.catalog.records.map((record) => record.logicalId)),
  );
  const families = Object.fromEntries(FAMILIES.map((family) => {
    const records = input.catalog.byFamily[family];
    const baseline = input.catalog.baselines.find((candidate) => candidate.family === family);
    if (!baseline) throw new Error(`missing lore baseline for family ${family}`);
    const kinds = Object.fromEntries(KINDS[family].map((kind) => [kind, metricForRecords(
      records.filter((record) => record.kind === kind), input.summaries, input.localOverlay,
      input.invalidRelationships?.[family]?.[kind] ?? 0,
      classifiedRejections.byId,
    )]));
    const invalidCount = Object.values(input.invalidRelationships?.[family] ?? {})
      .reduce<number>((sum, count) => sum + (count ?? 0), 0);
    const metric = metricForRecords(records, input.summaries, input.localOverlay, invalidCount, classifiedRejections.byId);
    const familyReport: LoreFamilyCoverage = {
      ...metric,
      baselineStatus: baseline.baselineStatus,
      expected: baseline.baselineStatus === "complete" ? baseline.expectedCount : null,
      percentage: baseline.baselineStatus === "complete" && baseline.expectedCount !== null
        ? percentage(baseline.expectedCount, metric.structured)
        : null,
      kinds,
    };
    return [family, familyReport];
  })) as LoreCoverageReport["families"];

  const familyReports = Object.values(families);
  const allComplete = familyReports.every((family) => family.baselineStatus === "complete" && family.expected !== null);
  const totals = familyReports.reduce((result, family) => {
    for (const field of AGGREGATE_FIELDS) {
      result[field] += family[field];
    }
    return result;
  }, emptyMetric());
  totals.importRejections = sumImportRejections(familyReports.map((family) => family.importRejections));
  totals.baselineStatus = allComplete ? "complete" : "missing";
  totals.expected = allComplete ? familyReports.reduce((sum, family) => sum + family.expected!, 0) : null;
  totals.percentage = totals.expected === null ? null : percentage(totals.expected, totals.structured);
  return LoreCoverageReportSchema.parse({
    families,
    totals,
    unattributedImportRejections: classifiedRejections.unattributed,
  });
}

export { KINDS as LORE_KINDS };
