import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { loadLoreCatalog } from "./catalog";
import { buildLoreCoverage, LoreCoverageReportSchema } from "./coverage";

const loreRoot = join(import.meta.dirname, "..", "__fixtures__", "lore");

describe("buildLoreCoverage", () => {
  it("reports fixed fields by family and kind without inventing missing-baseline percentages", () => {
    const catalog = loadLoreCatalog(loreRoot, "4.4-fixture");
    const report = buildLoreCoverage({ catalog, summaries: [], localOverlay: new Map() });

    expect(report.families.mission).toMatchObject({
      baselineStatus: "missing", expected: null, structured: 1, summaries: 0,
      reviewed: 0, autoGenerated: 0, fullText: 0, missingSourceEvidence: 0,
      rejectedLaterVersion: 0, rejectedAmbiguousVersion: 0, invalidRelationships: 0,
      importRejections: { unknownKind: 0, missingText: 0, ambiguousRelease: 0, malformedSource: 0 },
      percentage: null,
    });
    expect(report.families.worldview.kinds.location).toEqual({
      baselineStatus: "missing", expected: null, structured: 1, summaries: 0,
      reviewed: 0, autoGenerated: 0, fullText: 0, missingSourceEvidence: 0,
      rejectedLaterVersion: 0, rejectedAmbiguousVersion: 0, invalidRelationships: 0,
      importRejections: { unknownKind: 0, missingText: 0, ambiguousRelease: 0, malformedSource: 0 },
      percentage: null,
    });
    expect(report.totals.percentage).toBeNull();
  });

  it("calculates a complete family percentage and counts only exact lore summaries", () => {
    const loaded = loadLoreCatalog(loreRoot, "4.4-fixture");
    const second = { ...loaded.byFamily.worldview[0]!, logicalId: "lore:worldview:location:second" };
    const catalog = {
      ...loaded,
      baselines: loaded.baselines.map((baseline) => baseline.family === "worldview" ? { ...baseline, expectedCount: 4 } : baseline),
      byFamily: { ...loaded.byFamily, worldview: [loaded.byFamily.worldview[0]!, second] },
      records: [...loaded.records, second],
    };
    const summaries = [
      { logicalId: "lore:worldview:location:belobog", entityKind: "lore", releaseId: "4.4-fixture", reviewStatus: "reviewed" },
      { logicalId: "lore:worldview:location:second", entityKind: "character", releaseId: "4.4-fixture", reviewStatus: "auto-generated" },
      { logicalId: "lore:worldview:location:belobog", entityKind: "lore", releaseId: "other", reviewStatus: "auto-generated" },
    ] as never;
    const report = buildLoreCoverage({ catalog, summaries, localOverlay: new Map() });
    expect(report.families.worldview).toMatchObject({ structured: 2, summaries: 1, reviewed: 1, autoGenerated: 0, percentage: 50 });
  });

  it("attributes exact import rejection categories without relabeling their meaning", () => {
    const catalog = loadLoreCatalog(loreRoot, "4.4-fixture");
    const report = buildLoreCoverage({ catalog, summaries: [], localOverlay: new Map(), importReport: {
      status: "rejected", releaseId: "4.4-fixture", acceptedCount: 0, rejectedCount: 4,
      inputChecksums: [], outputChecksum: null, warnings: [], rejection: {
        reason: "adapter-rejected", sourcePaths: [], recoveryNames: [], items: [
          { sourcePath: "a", logicalId: null, reason: "ambiguous-release", detail: "release-evidence-mismatch" },
          { sourcePath: "b", logicalId: "lore:mission:trailblaze:silent-star", reason: "missing-text", detail: "no-allowlisted-text" },
          { sourcePath: "c", logicalId: "lore:worldview:location:belobog", reason: "unknown-kind", detail: "category-not-mapped" },
          { sourcePath: "d", logicalId: "lore:unknown", reason: "malformed-source", detail: "invalid-directory-json" },
        ],
      },
    } });
    expect(report.families.mission.importRejections).toEqual({ unknownKind: 0, missingText: 1, ambiguousRelease: 0, malformedSource: 0 });
    expect(report.families.worldview.kinds.location.importRejections.unknownKind).toBe(1);
    expect(report.totals).toMatchObject({
      missingSourceEvidence: 0,
      rejectedAmbiguousVersion: 0,
      rejectedLaterVersion: 0,
      importRejections: { unknownKind: 1, missingText: 1, ambiguousRelease: 0, malformedSource: 0 },
    });
    expect(report.unattributedImportRejections).toEqual({ unknownKind: 0, missingText: 0, ambiguousRelease: 1, malformedSource: 1 });
    const ignored = buildLoreCoverage({ catalog, summaries: [], localOverlay: new Map(), importReport: { ...reportFixture, releaseId: "4.5" } });
    expect(ignored.unattributedImportRejections.ambiguousRelease).toBe(0);
  });

  it("enforces summary partitions and family-derived rejection totals in the schema", () => {
    const report = buildLoreCoverage({ catalog: loadLoreCatalog(loreRoot, "4.4-fixture"), summaries: [], localOverlay: new Map() });
    const badPartition = structuredClone(report);
    badPartition.families.worldview.summaries = 1;
    badPartition.families.worldview.reviewed = 1;
    badPartition.families.worldview.autoGenerated = 1;
    expect(() => LoreCoverageReportSchema.parse(badPartition)).toThrow(/partition|reviewed|summary|component/i);
    const badTotal = structuredClone(report);
    badTotal.totals.importRejections.unknownKind = 1;
    expect(() => LoreCoverageReportSchema.parse(badTotal)).toThrow(/sum|total|family/i);
    const badFamily = structuredClone(report);
    badFamily.families.worldview.kinds.location.importRejections.missingText = 1;
    expect(() => LoreCoverageReportSchema.parse(badFamily)).toThrow(/sum|total|kind/i);
  });
});

const reportFixture = {
  status: "rejected" as const, acceptedCount: 0, rejectedCount: 1, inputChecksums: [], outputChecksum: null,
  warnings: [] as [], rejection: { reason: "adapter-rejected" as const, sourcePaths: [], recoveryNames: [], items: [
    { sourcePath: "a", logicalId: null, reason: "ambiguous-release" as const, detail: "release-evidence-mismatch" as const },
  ] },
};
