import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { loadLoreCatalog } from "./catalog";
import { buildLoreCoverage } from "./coverage";

const loreRoot = join(import.meta.dirname, "..", "__fixtures__", "lore");

describe("buildLoreCoverage", () => {
  it("reports fixed fields by family and kind without inventing missing-baseline percentages", () => {
    const catalog = loadLoreCatalog(loreRoot, "4.4-fixture");
    const report = buildLoreCoverage({ catalog, summaries: [], localOverlay: new Map() });

    expect(report.families.mission).toMatchObject({
      baselineStatus: "missing", expected: null, structured: 1, summaries: 0,
      reviewed: 0, autoGenerated: 0, fullText: 0, missingSourceEvidence: 0,
      rejectedLaterVersion: 0, rejectedAmbiguousVersion: 0, invalidRelationships: 0,
      percentage: null,
    });
    expect(report.families.worldview.kinds.location).toEqual({
      baselineStatus: "missing", expected: null, structured: 1, summaries: 0,
      reviewed: 0, autoGenerated: 0, fullText: 0, missingSourceEvidence: 0,
      rejectedLaterVersion: 0, rejectedAmbiguousVersion: 0, invalidRelationships: 0,
      percentage: null,
    });
    expect(report.totals.percentage).toBeNull();
  });

  it("calculates a complete family percentage and counts only exact lore summaries", () => {
    const loaded = loadLoreCatalog(loreRoot, "4.4-fixture");
    const second = { ...loaded.byFamily.worldview[0]!, logicalId: "lore:worldview:location:second" };
    const catalog = {
      ...loaded,
      baselines: loaded.baselines.map((baseline) => baseline.family === "worldview" ? { ...baseline, expectedCount: 4 } : baseline),
      byFamily: { ...loaded.byFamily, worldview: [loaded.byFamily.worldview[0]!, second] },
      records: [...loaded.records, second],
    };
    const summaries = [
      { logicalId: "lore:worldview:location:belobog", entityKind: "lore", releaseId: "4.4-fixture", reviewStatus: "reviewed" },
      { logicalId: "lore:worldview:location:second", entityKind: "character", releaseId: "4.4-fixture", reviewStatus: "auto-generated" },
      { logicalId: "lore:worldview:location:belobog", entityKind: "lore", releaseId: "other", reviewStatus: "auto-generated" },
    ] as never;
    const report = buildLoreCoverage({ catalog, summaries, localOverlay: new Map() });
    expect(report.families.worldview).toMatchObject({ structured: 2, summaries: 1, reviewed: 1, autoGenerated: 0, percentage: 50 });
  });

  it("counts only same-release import rejection reasons through fixed buckets", () => {
    const catalog = loadLoreCatalog(loreRoot, "4.4-fixture");
    const report = buildLoreCoverage({ catalog, summaries: [], localOverlay: new Map(), importReport: {
      status: "rejected", releaseId: "4.4-fixture", acceptedCount: 0, rejectedCount: 3,
      inputChecksums: [], outputChecksum: null, warnings: [], rejection: {
        reason: "adapter-rejected", sourcePaths: [], recoveryNames: [], items: [
          { sourcePath: "a", logicalId: null, reason: "ambiguous-release", detail: "release-evidence-mismatch" },
          { sourcePath: "b", logicalId: "lore:mission:x", reason: "missing-text", detail: "no-allowlisted-text" },
          { sourcePath: "c", logicalId: "lore:mission:y", reason: "unknown-kind", detail: "category-not-mapped" },
        ],
      },
    } });
    expect(report.totals).toMatchObject({ rejectedAmbiguousVersion: 1, missingSourceEvidence: 2, rejectedLaterVersion: 0 });
    const ignored = buildLoreCoverage({ catalog, summaries: [], localOverlay: new Map(), importReport: { ...reportFixture, releaseId: "4.5" } });
    expect(ignored.totals.rejectedAmbiguousVersion).toBe(0);
  });
});

const reportFixture = {
  status: "rejected" as const, acceptedCount: 0, rejectedCount: 1, inputChecksums: [], outputChecksum: null,
  warnings: [] as [], rejection: { reason: "adapter-rejected" as const, sourcePaths: [], recoveryNames: [], items: [
    { sourcePath: "a", logicalId: null, reason: "ambiguous-release" as const, detail: "release-evidence-mismatch" as const },
  ] },
};
